import { ClerkLoaded, ClerkLoading, ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { config } from "dotenv";
import Loader from "./components/Loader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
config({ path: "../" });
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ClerkLoading>
            <Loader />
          </ClerkLoading>
          <ClerkLoaded>
            <div>{children}</div>
            <div id="photo-picker-element"></div>
          </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}
